#--------------------------------------------------------
#
#GitHubActions
#
# CopyLeft ...
#---------------------------------------------------------

name: DevOpsBasicsTest-FirstAction
on:
  push:
    branches:
      -master
      
jobs:
  myTest:
    runs-on: windows-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello, World! from myTest job"
  
    
    
  

