#--------------------------------------------------------
#
#GitHubActions
#
# CopyLeft ...
#---------------------------------------------------------

name: DevOpsBasicsTest-SecondAction
on:
  push:
    branches:
     - master
      
jobs:
  myTest:
    runs-on: windows-latest
    
    steps:
    - name: Print Hello Message
      run: echo "Hello, World! from myTest job"
      
    - name: Execute few commands
      run: |
        echo "Hello Message 1"
        echo "Hello Message 2"
    
    - name: List current folder
      run: ls

    - name: Git Clone my repo
      uses: actions/checkout@v1

  myDeploy:
    runs-on: windows-latest
    needs: [myTest]
    
    steps:
    - name: Print Hello Message
      run: echo "Hello, World! from myDeploy job"
